In [23]:
import numpy as np
import sympy as sp
np.random.seed(44)
A=np.random.randint(0,10,(5,5))
print(A)



[[4 3 1 3 0]
 [4 3 8 7 7]
 [6 9 3 7 3]
 [3 6 5 4 5]
 [9 1 8 7 4]]


In [24]:
A[0] = A[0]/4
A

array([[1, 0, 0, 0, 0],
       [4, 3, 8, 7, 7],
       [6, 9, 3, 7, 3],
       [3, 6, 5, 4, 5],
       [9, 1, 8, 7, 4]])

In [25]:
A[1]=A[1] - 4*A[0]
A

array([[1, 0, 0, 0, 0],
       [0, 3, 8, 7, 7],
       [6, 9, 3, 7, 3],
       [3, 6, 5, 4, 5],
       [9, 1, 8, 7, 4]])

In [26]:
A[2]=A[2] - 6*A[0]
A

array([[1, 0, 0, 0, 0],
       [0, 3, 8, 7, 7],
       [0, 9, 3, 7, 3],
       [3, 6, 5, 4, 5],
       [9, 1, 8, 7, 4]])

In [27]:
A[3]=A[3] - 3*A[0]
A

array([[1, 0, 0, 0, 0],
       [0, 3, 8, 7, 7],
       [0, 9, 3, 7, 3],
       [0, 6, 5, 4, 5],
       [9, 1, 8, 7, 4]])

In [28]:
A[4]=A[4] - 9*A[0]
A

array([[1, 0, 0, 0, 0],
       [0, 3, 8, 7, 7],
       [0, 9, 3, 7, 3],
       [0, 6, 5, 4, 5],
       [0, 1, 8, 7, 4]])

In [29]:
A[1]=1/3*A[1]
A

array([[1, 0, 0, 0, 0],
       [0, 1, 2, 2, 2],
       [0, 9, 3, 7, 3],
       [0, 6, 5, 4, 5],
       [0, 1, 8, 7, 4]])

In [30]:
A[2]=A[2] - 9*A[1]
A

array([[  1,   0,   0,   0,   0],
       [  0,   1,   2,   2,   2],
       [  0,   0, -15, -11, -15],
       [  0,   6,   5,   4,   5],
       [  0,   1,   8,   7,   4]])

In [31]:
A[3]=A[3] - 6*A[1]
A

array([[  1,   0,   0,   0,   0],
       [  0,   1,   2,   2,   2],
       [  0,   0, -15, -11, -15],
       [  0,   0,  -7,  -8,  -7],
       [  0,   1,   8,   7,   4]])

In [33]:
A[4]=A[4] - A[1]
A

array([[  1,   0,   0,   0,   0],
       [  0,   1,   2,   2,   2],
       [  0,   0, -15, -11, -15],
       [  0,   0,  -7,  -8,  -7],
       [  0,   0,   6,   5,   2]])

In [34]:
A[2]=1/-15*A[2]
A

array([[ 1,  0,  0,  0,  0],
       [ 0,  1,  2,  2,  2],
       [ 0,  0,  1,  0,  1],
       [ 0,  0, -7, -8, -7],
       [ 0,  0,  6,  5,  2]])

In [35]:
A[1]=A[1] - 2*A[2]
A

array([[ 1,  0,  0,  0,  0],
       [ 0,  1,  0,  2,  0],
       [ 0,  0,  1,  0,  1],
       [ 0,  0, -7, -8, -7],
       [ 0,  0,  6,  5,  2]])

In [36]:
A[3]=A[3] + 7*A[2]
A

array([[ 1,  0,  0,  0,  0],
       [ 0,  1,  0,  2,  0],
       [ 0,  0,  1,  0,  1],
       [ 0,  0,  0, -8,  0],
       [ 0,  0,  6,  5,  2]])

In [37]:
A[4]=A[4] - 6*A[2]
A

array([[ 1,  0,  0,  0,  0],
       [ 0,  1,  0,  2,  0],
       [ 0,  0,  1,  0,  1],
       [ 0,  0,  0, -8,  0],
       [ 0,  0,  0,  5, -4]])

In [38]:
A[3]=1/-8* A[3]
A

array([[ 1,  0,  0,  0,  0],
       [ 0,  1,  0,  2,  0],
       [ 0,  0,  1,  0,  1],
       [ 0,  0,  0,  1,  0],
       [ 0,  0,  0,  5, -4]])

In [39]:
A[1]=A[1] - 2*A[3]
A

array([[ 1,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0],
       [ 0,  0,  1,  0,  1],
       [ 0,  0,  0,  1,  0],
       [ 0,  0,  0,  5, -4]])

In [40]:
A[4]=A[4] - 5*A[3]
A

array([[ 1,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0],
       [ 0,  0,  1,  0,  1],
       [ 0,  0,  0,  1,  0],
       [ 0,  0,  0,  0, -4]])

In [41]:
A[4]=1/-4*A[4]
A

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [42]:
A[2]=A[2] - A[4]
A

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])