In [ ]:
#que 3

In [2]:
import numpy as np
import sympy as sp
np.random.seed(44)
A=np.random.randint(0,10,(5,5))
print(A)



[[4 3 1 3 0]
 [4 3 8 7 7]
 [6 9 3 7 3]
 [3 6 5 4 5]
 [9 1 8 7 4]]


In [3]:
U,S,Vt=np.linalg.svd(A)
print(U)

[[-0.2007194  -0.24168647 -0.43523977  0.02505001 -0.8433494 ]
 [-0.51894652  0.35318247  0.50857649  0.54510449 -0.22398147]
 [-0.49243967 -0.69464111 -0.15608042  0.29351742  0.40554078]
 [-0.39698364 -0.20934837  0.48395407 -0.74202485 -0.11732361]
 [-0.53880738  0.53897753 -0.54161209 -0.25589107  0.2456948 ]]


In [4]:
print(S)

[25.18156279  7.79202654  5.58170325  1.41897822  0.06563335]


In [5]:
print(Vt)

[[-0.47151637 -0.37772334 -0.48150259 -0.51789668 -0.36733591]
 [ 0.06428237 -0.85143379  0.48317704 -0.02307752  0.19218649]
 [-0.72841247  0.21093897  0.2243051  -0.12428378  0.59930025]
 [-0.34346664 -0.25082834 -0.34589301  0.83593    -0.02636043]
 [ 0.35353363 -0.1580363  -0.60393745 -0.13048001  0.68430477]]


In [6]:
rank_2_approximation = np.dot(U[:, :2], np.dot(np.diag(S[:2]), Vt[:2, :]))
rank_3_approximation = np.dot(U[:, :3], np.dot(np.diag(S[:3]), Vt[:3, :]))

print("\nRank 2 approximation of matrix A:")
print(rank_2_approximation)
print("\nRank 3 approximation of matrix A:")
print(rank_3_approximation)


Rank 2 approximation of matrix A:
[[2.26218727 3.51261894 1.523788   2.66113177 1.49474211]
 [6.33862695 2.59289302 7.62192694 6.70430443 5.32920186]
 [5.49905308 9.29244404 3.35555103 6.54703711 3.51487196]
 [4.60873229 5.16487472 4.02524015 5.21488654 3.35863148]
 [6.66750809 1.5491651  8.56224465 6.92990896 5.79114884]]

Rank 3 approximation of matrix A:
[[4.03177741 3.0001682  0.97886586 2.96306421 0.03881453]
 [4.27086567 3.19169033 8.25866699 6.35149719 7.03044929]
 [6.13364207 9.10867516 3.16013765 6.65531247 2.99276484]
 [2.64108043 5.73468162 4.63115281 4.87916026 4.97751404]
 [8.86958494 0.91147172 7.88414388 7.3056335  3.97939348]]
